# Usar una imagen base de Python delgada
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema necesarias para Scapy
RUN apt-get update && apt-get install -y libpcap-dev

# Copiar el archivo de requerimientos e instalar dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación
COPY . .

# Comando por defecto para ejecutar la aplicación
CMD ["python", "sniffer.py"]